"""Local plotting defaults; no dependency on an external research checkout."""

FIGSIZE = (10, 5)
FONT_SIZE_AXIS_LABEL = 12
FONT_WEIGHT_AXIS_LABEL = "normal"
FONT_SIZE_TICK = 10
FONT_SIZE_TITLE = 14
FONT_WEIGHT_TITLE = "normal"
FONT_SIZE_LEGEND = 10
GRID_ALPHA = 0.25
REFLINE_STYLE = "--"
REFLINE_WIDTH = 1
REFLINE_ALPHA = 0.5
SUBPLOT_LEFT = 0.10
SUBPLOT_RIGHT = 0.97
SUBPLOT_TOP = 0.90
SUBPLOT_BOTTOM = 0.15
DPI = 150
